feat: added create interview | 92
chacrunaa/interview-fe pull request #29
Opened 2024-05-21 15:44 UTC by dilya3228

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/CreateInterview.tsx
> +  const [companyName, setCompanyName] = useState<string>('');
Нужно убрать такое количество стейтов. Изменение одного стейта ведёт к перерендеру компонента. Поэтому при печате в один инпут перерендирвается вся форма

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/CreateInterview.tsx
> +  const [companyName, setCompanyName] = useState<string>('');
Видео - https://skrinshoter.ru/vPqW80KiSGW?a

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/CreateInterview.tsx
> +      console.log('Success:', data);
Это зачем?

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/CreateInterview.tsx
> +          <Select
Мы должны использовать одинаковые компоненты для всех разделов, эти селекты импортированы из mui, а нужно переиспользовать с главной.

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/CreateInterview.tsx
> +  return (
Нужно взглянуть эту разметку Диме, для меня она выглядит сложно

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/CreateInterview.tsx
> +          <FormControlLabel
мэпинг хотябы

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/CreateInterview.tsx
> +  function valuetext(value: number) {
проверяй хоть немного за gpt

2024-05-21 17:14 UTC, ArtemMayorov commented on src/components/CreateInterview/helpers/types.ts
> +export type StatusType = 'processing' | 'failure' | 'successful';
типы взять из существующих

2024-05-22 04:58 UTC, chacrunaa requested changes

2024-05-22 04:58 UTC, chacrunaa commented on src/components/CreateInterview/CreateInterview.tsx
> +  const [offer, setOffer] = useState<number[]>([100000, 300000]);
числа лучше выносить в переменные

2024-05-22 04:58 UTC, chacrunaa commented on src/components/CreateInterview/CreateInterview.tsx
> +    return `${value}`;
можно было бы привести к строке без функции

2024-05-22 04:58 UTC, chacrunaa commented on src/components/CreateInterview/CreateInterview.tsx
> +  const handleGradeChange = (event: any) => {
убрать any

2024-05-22 04:58 UTC, chacrunaa commented on src/components/CreateInterview/CreateInterview.tsx
> +  const handleStageChange = (event: any) => {
any

2024-05-22 04:58 UTC, chacrunaa commented on src/components/CreateInterview/CreateInterview.tsx
> +      typeof value === 'string' ? (value.split(',') as StageType[]) : value,
использование as  - это не хорошая практика, особенно частое использование

2024-05-22 04:58 UTC, chacrunaa commented on src/components/CreateInterview/helpers/types.ts
> +  maxoffer: number;
если нет мин и макс, то параметр должен быть необязательным. Если лишь одно значение зп, то мы все равно должны передать? 
Например, minoffer === 90 000 и  maxoffer === 90 000 

?

2024-05-24 08:55 UTC, chacrunaa requested changes

2024-05-24 08:55 UTC, chacrunaa commented on src/components/CreateInterview/CreateInterview.tsx
> +    const { ...rest } = formData;
rest  переименуй на data

2024-05-24 08:55 UTC, chacrunaa commented on src/components/castomForm/GetEditor/Editors/NumberRange/NumberRange.tsx
> +    const minOfferPath: Path<FormType> = 'minoffer' as Path<FormType>;
Не хардкодить данные поля, а передать их через пропсы  в дефс для обращения
as Path<FormType> в таком случае будет не нужен. 
Иначе  NumberRange  не является универсальным

2024-05-24 08:55 UTC, chacrunaa commented on src/components/castomForm/GetEditor/Editors/NumberRange/NumberRange.tsx
> +    const maxOfferPath: Path<FormType> = 'maxoffer' as Path<FormType>;
аналогично

2024-05-24 08:55 UTC, chacrunaa commented on src/components/castomForm/GetEditor/Editors/NumberRange/NumberRange.tsx
> +                    <Controller
не нужно два контроллера

2024-05-24 08:55 UTC, chacrunaa commented on src/components/castomForm/GetEditor/Editors/NumberRange/NumberRange.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
убрать

2024-05-24 11:33 UTC, chacrunaa approved these changes

2024-05-24 11:34 UTC, merged